# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the p-SWAMP Project.

"""The PMU source, and the applications reading it.

A recorded Nordic 44 stream replayed at real-time pace, rather than a live
simulator or a broker. Three reasons, in order of weight: the disturbance is
reproducible, so a page can be checked against a known event instead of whatever
the grid happens to be doing; it needs no second process, which is what lets the
whole thing stay one container; and it goes in through the same ``io`` seam a
broker would, so swapping one back in is a constructor argument.

The recording is regenerated by ``app/server-python/tools/record_n44_dataset.py``
(see its docstring -- it needs p-SWAMP's simulator, which is not a dependency of
this project).
"""

from pathlib import Path

from pswamp.app_templates.time_window_app import TimeWindowApp
from pswamp.utils.time_window_labeled import TimeWindowLabeled

from .recorded_io import Recording

# Beside the code that reads it, and inside src/ so the Dockerfile's existing
# `COPY src/` picks it up with no build change.
RECORDING_PATH = Path(__file__).parent / "data" / "n44_line_trip_50hz.npz"

# Seconds of history the shared measurement window holds. Wide enough to see the
# frequency traces separate and recover across the line trip, which is the whole
# point of the recording.
WINDOW_SECONDS = 30

# Seconds of frequency history the islanding detector considers, and how often it
# re-evaluates. Both are p-SWAMP's defaults for this application.
ISLANDING_WINDOW_SECONDS = 10
ISLANDING_EVAL_HZ = 1


def load_recording() -> Recording:
    return Recording.load(RECORDING_PATH)


class CountingTimeWindowLabeled(TimeWindowLabeled):
    """A time window that also says *how much* is new since you last looked.

    p-SWAMP's ``TimeWindow`` tracks only ``_k``, the write cursor, which wraps —
    so a consumer can see the current contents but cannot tell how many rows
    arrived since its previous read. Sending only the new samples over a socket
    (rather than the whole window, several times a second) needs exactly that.

    Kept here as a subclass so this project needs no change to p-SWAMP. The
    counter and ``snapshot`` are small, additive and generally useful, and belong
    in ``utils/time_window.py`` eventually — see
    ``doc/WIP-context-port-from-qt-to-web-frontend.md`` §11.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.n_appended = 0

    def append(self, new_time, new_data):
        super().append(new_time, new_data)
        # Safe outside the lock: only the single application thread appends.
        self.n_appended += 1

    def snapshot(self, col_idx=slice(None)):
        """Lock-protected ``(n_appended, time, data)`` copy.

        The count is read under the same lock as the data, so the two describe
        the same instant; reading them separately can miss or double-count rows
        appended in between.
        """
        with self.lock:
            return (
                self.n_appended,
                self.get_time().copy(),
                self.get_col(col_idx).copy(),
            )


class MeasurementStoreApp(TimeWindowApp):
    """Keeps a window of every channel, and analyses none of them.

    The pages that plot measurements -- the time window, the phasor dial -- need
    the same recent history that an analysis application keeps, but no analysis.
    Rather than have each page hold its own window and its own reader, they share
    this one: a single application whose only job is to be read from.

    It is a real ``TimeWindowApp`` and not a bespoke buffer so that reading it is
    the same operation as reading any other application's window, and so it
    reports status alongside them.
    """

    def __init__(self, **kwargs):
        super().__init__(report_status=True, **kwargs)
        self.status = "OK"
        # Swap in the counting window. Safe here because TimeWindowApp only
        # *creates* self.tw during __init__ -- the first append happens later,
        # from the run loop, which has not started yet.
        self.tw = CountingTimeWindowLabeled(
            header={
                row: list(self.tw.header[row]) for row in self.tw.header.dtype.names
            },
            n_samples=self.tw.n_samples,
            dtype=self.decoder.data_dtype,
        )

    def run_analysis(self, t, measurements):
        return None
