/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/grid/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grid Model
         * @description The static Nordic 44 topology: buses, branches, PMU sites and a bounding
         *     box. Fetched once per page mount and cacheable, as above.
         */
        get: operations["grid_model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge
         * @description Mark an alarm as seen by an operator.
         */
        post: operations["islanding_acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotate
         * @description Attach a free-text operator note to an alarm.
         *
         *     The Qt dialogue's "Annotate" button. Upstream records this as a
         *     ``user_message`` event on the alarm rather than as a state change, so the
         *     same event type is used here and the two agree on the wire.
         */
        post: operations["islanding_annotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/silence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Silence
         * @description Stop an alarm from asserting itself, without resolving it.
         */
        post: operations["islanding_silence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-report/mean-voltage/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Mean Voltage
         * @description Start a mean-voltage report over a range of the source. The result arrives on the socket.
         */
        post: operations["pmu_report_run_mean_voltage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Back
         * @description Jump one sample back: a seek to the previous instant.
         */
        post: operations["pmu_test_streamer_back"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forward
         * @description Release the next sample now, playing or paused.
         */
        post: operations["pmu_test_streamer_forward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play
         * @description Start advancing this client through the recorded stream.
         */
        post: operations["pmu_test_streamer_play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seek
         * @description Continue from an absolute position in the source.
         */
        post: operations["pmu_test_streamer_seek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speed
         * @description Change how fast this client's replay runs relative to real time.
         */
        post: operations["pmu_test_streamer_speed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop
         * @description Pause this client where it is in the stream.
         */
        post: operations["pmu_test_streamer_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference-subapp/count/bump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bump
         * @description Add one to this client's count.
         */
        post: operations["reference_subapp_bump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference-subapp/count/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Put this client's count back to zero.
         */
        post: operations["reference_subapp_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Channels
         * @description Every selectable channel, for the picker. Static for the process, so it is
         *     a plain GET rather than part of the socket protocol.
         */
        get: operations["time_window_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resync
         * @description Ask for the whole window again rather than the next delta.
         *
         *     The escape hatch for a client whose buffer no longer matches what the server
         *     thinks it has -- a dropped append, a chart remounted mid-stream.
         */
        post: operations["time_window_resync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Channels
         * @description Choose which channels this browser's measurement view plots.
         */
        post: operations["time_window_select_channels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe for Docker/k8s, and the compose healthcheck. Cheap and
         *     side-effect-free: the server has no external dependencies, so "the process is
         *     up and serving" is the whole health story — there is nothing a separate
         *     readiness probe could usefully check. Deliberately at the root rather than
         *     under /api: it is the process's health, not any one app's.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alarm */
        Alarm: {
            /** App Name */
            app_name: string;
            /** App Uuid */
            app_uuid: string;
            /** Events */
            events: components["schemas"]["AlarmEvent"][];
            /**
             * Status
             * @enum {string}
             */
            status: "unseen" | "acknowledged" | "silenced" | "not_critical";
            /**
             * T End
             * @default null
             */
            t_end: number | null;
            /** T Start */
            t_start: number;
            /** Uuid */
            uuid: string;
        };
        /** AlarmEvent */
        AlarmEvent: {
            /** Message */
            message: string;
            /** T */
            t: number;
            /**
             * Type
             * @enum {string}
             */
            type: "init" | "not_critical" | "acknowledge" | "silence" | "user_message";
        };
        /** AlarmList */
        AlarmList: {
            /** Alarms */
            alarms: components["schemas"]["Alarm"][];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * AlarmNote
         * @description Body of POST /alarms/{alarm_uuid}/annotate.
         */
        AlarmNote: {
            /**
             * Message
             * @description The operator's note. Longer than 500 characters is truncated rather than rejected, so a slip cannot lose what was typed.
             */
            message: string;
        };
        /** AppStatus */
        AppStatus: {
            /** App Name */
            app_name: string;
            /** Received At */
            received_at: number;
            /** Stale */
            stale: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "Alert" | "Emergency" | "Initializing..." | "Undefined";
            /** T */
            t: number;
            /** Uuid */
            uuid: string;
        };
        /** AppStatusTable */
        AppStatusTable: {
            /** Apps */
            apps: components["schemas"]["AppStatus"][];
            replay: components["schemas"]["ReplayStatus"];
            /** Server Time */
            server_time: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * Channel
         * @description One column of a labelled time window.
         *
         *     Flattened from p-SWAMP's three-row header, plus a precomputed display label so
         *     the client never has to join the parts itself.
         */
        Channel: {
            /** Channel */
            channel: string;
            /** Idx */
            idx: number;
            /** Label */
            label: string;
            /** Measurement */
            measurement: string;
            /** Station */
            station: string;
        };
        /**
         * ChannelCatalogue
         * @description Body of ``GET /api/time-window/channels``: every selectable channel.
         *
         *     Static for the life of the process, which is why it is a plain GET rather than
         *     something pushed down the socket. Declared as a model so the catalogue is in
         *     the contract -- it used to be built as a hand-dumped dict, which published as
         *     a bare `object` and left the client casting an implicitly-`any` response.
         */
        ChannelCatalogue: {
            /** Channels */
            channels: components["schemas"]["Channel"][];
        };
        /**
         * ChannelSelection
         * @description Body of POST /selection.
         */
        ChannelSelection: {
            /**
             * Channels
             * @description Channel indices, as listed by GET /channels.
             * @example [
             *       3,
             *       17,
             *       204
             *     ]
             */
            channels: number[];
        };
        /**
         * CommandAck
         * @description The reply to every command POST.
         *
         *     Deliberately NOT the resulting state. That arrives on whichever socket the
         *     page has open, on the server's own schedule, so state has exactly one path
         *     and there is no ordering for a client to reconcile between two of them. What
         *     this carries is only "the command was understood and applied, and here is
         *     what it was" -- enough to log and to assert on, and nothing a page renders.
         */
        CommandAck: {
            /** Applied */
            applied: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** GridBranch */
        GridBranch: {
            /** From Bus */
            from_bus: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "line" | "trafo";
            /** Name */
            name: string;
            /** To Bus */
            to_bus: string;
        };
        /** GridBus */
        GridBus: {
            /** Area */
            area?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name: string;
            /** V Nom */
            v_nom?: number | null;
        };
        /**
         * GridModel
         * @description Static topology. Served over HTTP rather than a socket: it never changes,
         *     it is worth caching, and putting it on the socket would make every page's
         *     hook handle a second message shape for no benefit.
         */
        GridModel: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Branches */
            branches: components["schemas"]["GridBranch"][];
            /** Buses */
            buses: components["schemas"]["GridBus"][];
            /** Pmus */
            pmus: components["schemas"]["PmuSite"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Reply to `GET /healthz`, the liveness/readiness probe.
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Island */
        Island: {
            /** Index */
            index: number;
            /** Mean Freq */
            mean_freq: number | null;
            /** Stations */
            stations: string[];
        };
        /** IslandingParameters */
        IslandingParameters: {
            /** Eval Freq */
            eval_freq: number;
            /** Mean Threshold */
            mean_threshold: number;
            /** Window Length */
            window_length: number;
        };
        /** IslandingResult */
        IslandingResult: {
            /** App Name */
            app_name: string;
            /** App Uuid */
            app_uuid: string;
            /** Islands */
            islands: components["schemas"]["Island"][];
            parameters: components["schemas"]["IslandingParameters"];
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "Alert" | "Emergency" | "Initializing..." | "Undefined";
            /** T */
            t: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * IslandingState
         * @description Both halves of the islanding page in one message.
         *
         *     Detection and alarms are separate concerns upstream -- different topics, one
         *     derived from the other -- but they change together and are read together, so
         *     splitting them across two sockets would only mean the page could render them
         *     inconsistently.
         *
         *     Declared here rather than in islanding/api.py, where it used to live: this
         *     module's whole job is to be the one place a message shape is named, and a
         *     shape defined next to its endpoint was the one exception.
         */
        IslandingState: {
            alarms: components["schemas"]["AlarmList"];
            /** @default null */
            islanding: components["schemas"]["IslandingResult"] | null;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * JobAck
         * @description Acknowledgement of a batch command. Never carries the result.
         */
        JobAck: {
            /**
             * Applied
             * @description Which operation was started.
             */
            applied: string;
            /**
             * Job Id
             * @description Server-side id of the running job.
             */
            job_id: string;
            /**
             * Request Id
             * @description Correlation id the resulting Report will carry: the caller's own if it supplied one, otherwise the job_id.
             */
            request_id: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** JobError */
        JobError: {
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * LineOutageEvent
         * @description One branch changing connection state, as the detector reports it.
         *
         *     ``stations`` and ``measurements`` come straight from the time window's
         *     header for the channels that flipped, so a single physical line trip
         *     normally appears with the station at each end -- the current on that branch
         *     goes to zero as seen from both.
         */
        LineOutageEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "disconnect" | "connect";
            /** Measurements */
            measurements: string[];
            /** Stations */
            stations: string[];
            /** T */
            t: number;
        };
        /**
         * LineOutageLog
         * @description Newest first. The detector is silent unless something changes, so this is
         *     a log of transitions rather than a snapshot of present state.
         */
        LineOutageLog: {
            /**
             * App Name
             * @default null
             */
            app_name: string | null;
            /**
             * App Uuid
             * @default null
             */
            app_uuid: string | null;
            /** Events */
            events: components["schemas"]["LineOutageEvent"][];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
            /**
             * Window Length
             * @default null
             */
            window_length: number | null;
        };
        /**
         * ModuleRef
         * @description Which module produced a result.
         */
        ModuleRef: {
            /** Name */
            name: string;
            /** Uuid */
            uuid: string;
        };
        /** Phasor */
        Phasor: {
            /** Ang */
            ang: number | null;
            /** Channel */
            channel: string;
            /**
             * Island
             * @default null
             */
            island: number | null;
            /** Mag */
            mag: number | null;
            /** Station */
            station: string;
        };
        /**
         * PhasorSnapshot
         * @description The most recent phasor per station.
         *
         *     ``mag_ref`` and ``ang_ref`` are sent rather than applied, so the client can
         *     offer per-unit and mean-angle-relative views as toggles -- which is what the
         *     Qt phasor plot does -- without the server having to guess which is wanted.
         */
        PhasorSnapshot: {
            /**
             * Ang Ref
             * @default null
             */
            ang_ref: number | null;
            /**
             * Mag Ref
             * @default null
             */
            mag_ref: number | null;
            /** Phasors */
            phasors: components["schemas"]["Phasor"][];
            /** T */
            t: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * PmuReportState
         * @description Everything the report page shows: results, what is still running, failures.
         */
        PmuReportState: {
            /**
             * Errors
             * @description Jobs that failed, newest last.
             */
            errors: components["schemas"]["JobError"][];
            /**
             * Pending
             * @description Request ids of jobs still running.
             */
            pending: string[];
            /**
             * Reports
             * @description Newest first, at most MAX_REPORTS.
             */
            reports: components["schemas"]["VoltageReport"][];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** PmuSite */
        PmuSite: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
        /**
         * PmuStreamState
         * @description The single message shape pushed to a client on connect and every change.
         *
         *     A sample message carries the row that just played; a control message (after
         *     play/stop/speed) carries none, and the page keeps showing the last one. The
         *     header rides on the opening message only.
         */
        PmuStreamState: {
            /**
             * Duration S
             * @description Length of one pass of the source, in seconds.
             */
            duration_s: number;
            /**
             * @description Channel table; sent on the opening message only.
             * @default null
             */
            header: components["schemas"]["StreamHeader"] | null;
            /**
             * Index
             * @description 0-based sample ordinal within the current pass.
             */
            index: number;
            /**
             * Mode
             * @description What the source can do; transport controls only make sense for replay.
             * @enum {string}
             */
            mode: "live" | "replay";
            /**
             * Passes
             * @description How many times this client's replay has looped.
             */
            passes: number;
            /** Playing */
            playing: boolean;
            /**
             * Position S
             * @description Seconds into the source; null before the first sample.
             */
            position_s: number | null;
            /**
             * @description The row that just played; null on a control-only update.
             * @default null
             */
            sample: components["schemas"]["Sample"] | null;
            /**
             * Speed
             * @description Replay speed factor; 1.0 is as recorded.
             */
            speed: number;
            /**
             * Total
             * @description How many samples one pass of the source holds.
             */
            total: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * ReferenceSubappState
         * @description The single message shape pushed to a client on connect and every change.
         *
         *     Keys are snake_case on the wire, and stay that way: the page reads the
         *     generated type for this model rather than a renamed mirror of it.
         */
        ReferenceSubappState: {
            /**
             * Count
             * @description This client's count. Replace with real state.
             */
            count: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * ReplayStatus
         * @description State of the PMU source feeding every application.
         */
        ReplayStatus: {
            /** Cursor */
            cursor: number;
            /** Data Rate */
            data_rate: number;
            /** Duration */
            duration: number;
            /** N Channels */
            n_channels: number;
            /** N Samples */
            n_samples: number;
            /** Playing */
            playing: boolean;
            /** Position */
            position: number;
            /** Source */
            source: string;
        };
        /**
         * RunMeanVoltage
         * @description Which part of the source to report over. Both bounds unset = all of it.
         */
        RunMeanVoltage: {
            /**
             * End S
             * @description Seconds into the source, exclusive.
             */
            end_s?: number | null;
            /**
             * Request Id
             * @description Caller's correlation id; the report carries it back. Defaults to the job id.
             */
            request_id?: string | null;
            /**
             * Start S
             * @description Seconds into the source, inclusive.
             */
            start_s?: number | null;
        };
        /**
         * Sample
         * @description One instant across every channel of a stream, in header order.
         */
        Sample: {
            /**
             * Mrid
             * @description The StreamHeader.stream_id this row belongs to.
             */
            mRID: string;
            /**
             * Namespace
             * @default live
             */
            namespace: string;
            /**
             * Quality
             * @description C37.118 STAT word, if any.
             * @default null
             */
            quality: number | null;
            /**
             * Timestamp
             * @default null
             */
            timestamp: string | null;
            /**
             * Values
             * @description One per header channel; null = missing.
             */
            values: (number | null)[];
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /** Seek */
        Seek: {
            /**
             * Position S
             * @description Seconds into the source to continue from.
             */
            position_s: number;
        };
        /** SetSpeed */
        SetSpeed: {
            /**
             * Speed
             * @description Replay speed factor.
             */
            speed: number;
        };
        /** StationVoltage */
        StationVoltage: {
            /**
             * Mean Voltage
             * @description Volts; null when the station had no values.
             */
            mean_voltage: number | null;
            /** Station */
            station: string;
        };
        /**
         * StreamChannel
         * @description One column of a stream — p-SWAMP's three header rows plus a unit.
         *
         *     ``mRID`` is the CIM equipment id when a deployment has one; it is the hook
         *     the grid-model track (STEP2 §6.9) attaches to, and ``None`` everywhere else.
         */
        StreamChannel: {
            /**
             * Channel
             * @description Display channel, e.g. "V_Magnitude".
             */
            channel: string;
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Measurement
             * @description Quantity key, e.g. "v_Magnitude" or "f".
             */
            measurement: string;
            /**
             * Station
             * @description PMU / bus name, e.g. "3000".
             */
            station: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "V" | "A" | "Hz" | "Hz/s" | "rad" | "";
        };
        /**
         * StreamHeader
         * @description What a stream carries: sent once, referenced by every sample's ``mRID``.
         */
        StreamHeader: {
            /**
             * Channels
             * @description Column order of Sample.values.
             */
            channels: components["schemas"]["StreamChannel"][];
            /**
             * Data Rate
             * @description Samples per second.
             */
            data_rate: number;
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Namespace
             * @default live
             */
            namespace: string;
            /**
             * Source
             * @description Provenance: a file, a PDC id.
             * @default
             */
            source: string;
            /**
             * Stream Id
             * @description What Sample.mRID refers to.
             */
            stream_id: string;
            /**
             * Timestamp
             * @default null
             */
            timestamp: string | null;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /**
         * TimeWindowSlice
         * @description A slice of the client's measurement window.
         *
         *     ``series`` is column-major -- one list per channel, parallel to ``channels``.
         *     That is the layout a streaming chart wants; row-major would force the client
         *     to transpose a matrix of a few hundred thousand numbers on every update.
         *
         *     ``mode`` is what keeps this affordable. A full window is tens of thousands of
         *     numbers and re-sending it several times a second is megabytes per second per
         *     client; an "append" carries only the samples added since the last message.
         *     The server sends "full" on connect and whenever the selection changes, and
         *     "append" the rest of the time. ``seq`` counts messages so a client can tell
         *     it missed one and ask for a fresh "full".
         */
        TimeWindowSlice: {
            /**
             * Channels
             * @default null
             */
            channels: components["schemas"]["Channel"][] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "full" | "append";
            /**
             * N Samples
             * @default null
             */
            n_samples: number | null;
            /**
             * Sampling Rate
             * @default null
             */
            sampling_rate: number | null;
            /** Seq */
            seq: number;
            /** Series */
            series: (number | null)[][];
            /** T */
            t: (number | null)[];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoltageReport
         * @description Mean voltage magnitude over ``n_samples`` rows of one stream, in volts.
         */
        VoltageReport: {
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Mean Voltage
             * @description Volts, across every voltage channel; null if none.
             */
            mean_voltage: number | null;
            module: components["schemas"]["ModuleRef"];
            /**
             * N Samples
             * @description How many source rows the report is over.
             */
            n_samples: number;
            /**
             * Namespace
             * @default live
             */
            namespace: string;
            /** Parameters */
            parameters?: {
                [key: string]: number | string | boolean | null;
            };
            /**
             * Range End
             * @default null
             */
            range_end: string | null;
            /**
             * Range Start
             * @default null
             */
            range_start: string | null;
            /**
             * Request Id
             * @description Set when this result answers a specific command (a job).
             * @default null
             */
            request_id: string | null;
            /** Stations */
            stations: components["schemas"]["StationVoltage"][];
            /** Stream Id */
            stream_id: string;
            /**
             * Timestamp
             * @default null
             */
            timestamp: string | null;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    grid_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridModel"];
                };
            };
        };
    };
    islanding_acknowledge: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    islanding_annotate: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    islanding_silence: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_report_run_mean_voltage: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunMeanVoltage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_back: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_forward: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_play: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_seek: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Seek"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_speed: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSpeed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_stop: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_subapp_bump: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_subapp_reset: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_window_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelCatalogue"];
                };
            };
        };
    };
    time_window_resync: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_window_select_channels: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
