/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/grid/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grid Model
         * @description The static Nordic 44 topology: buses, branches, PMU sites and a bounding
         *     box. Fetched once per page mount and cacheable, as above.
         */
        get: operations["grid_model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge
         * @description Mark an alarm as seen by an operator.
         */
        post: operations["islanding_acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotate
         * @description Attach a free-text operator note to an alarm.
         *
         *     The Qt dialogue's "Annotate" button. Upstream records this as a
         *     ``user_message`` event on the alarm rather than as a state change, so the
         *     same event type is used here and the two agree on the wire.
         */
        post: operations["islanding_annotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/islanding/alarms/{alarm_uuid}/silence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Silence
         * @description Stop an alarm from asserting itself, without resolving it.
         */
        post: operations["islanding_silence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/excursion/auto-pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Pause
         * @description Tell the excursion module whether to pause the player on an excursion.
         */
        post: operations["pmu_test_streamer_auto_pause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause
         * @description Pause the recording at the cursor.
         */
        post: operations["pmu_test_streamer_pause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play
         * @description Play the recording from the cursor.
         */
        post: operations["pmu_test_streamer_play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seek
         * @description Move to an offset into the recording; with an end, play only that chunk.
         */
        post: operations["pmu_test_streamer_seek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Source
         * @description Read another source: a recording lands paused at its start, a live feed
         *     is followed from now.
         */
        post: operations["pmu_test_streamer_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speed
         * @description Change the replay speed.
         */
        post: operations["pmu_test_streamer_speed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/playback/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step
         * @description Step ``n`` frames, forward or back.
         */
        post: operations["pmu_test_streamer_step"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pmu-test-streamer/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summary
         * @description Ask the range summary module to summarize a range of a recording. The
         *     answer arrives on the socket as ``summary``.
         */
        post: operations["pmu_test_streamer_summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference-subapp/count/bump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bump
         * @description Add one to this client's count.
         */
        post: operations["reference_subapp_bump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference-subapp/count/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Put this client's count back to zero.
         */
        post: operations["reference_subapp_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Channels
         * @description Every selectable channel, for the picker. Static for the process, so it is
         *     a plain GET rather than part of the socket protocol.
         */
        get: operations["time_window_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resync
         * @description Ask for the whole window again rather than the next delta.
         *
         *     The escape hatch for a client whose buffer no longer matches what the server
         *     thinks it has -- a dropped append, a chart remounted mid-stream.
         */
        post: operations["time_window_resync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-window/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Channels
         * @description Choose which channels this browser's measurement view plots.
         */
        post: operations["time_window_select_channels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe for Docker/k8s, and the compose healthcheck. Cheap and
         *     side-effect-free: the server has no external dependencies, so "the process is
         *     up and serving" is the whole health story — there is nothing a separate
         *     readiness probe could usefully check. Deliberately at the root rather than
         *     under /api: it is the process's health, not any one app's.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alarm */
        Alarm: {
            /** App Name */
            app_name: string;
            /** App Uuid */
            app_uuid: string;
            /** Events */
            events: components["schemas"]["AlarmEvent"][];
            /**
             * Status
             * @enum {string}
             */
            status: "unseen" | "acknowledged" | "silenced" | "not_critical";
            /**
             * T End
             * @default null
             */
            t_end: number | null;
            /** T Start */
            t_start: number;
            /** Uuid */
            uuid: string;
        };
        /** AlarmEvent */
        AlarmEvent: {
            /** Message */
            message: string;
            /** T */
            t: number;
            /**
             * Type
             * @enum {string}
             */
            type: "init" | "not_critical" | "acknowledge" | "silence" | "user_message";
        };
        /** AlarmList */
        AlarmList: {
            /** Alarms */
            alarms: components["schemas"]["Alarm"][];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * AlarmNote
         * @description Body of POST /alarms/{alarm_uuid}/annotate.
         */
        AlarmNote: {
            /**
             * Message
             * @description The operator's note. Longer than 500 characters is truncated rather than rejected, so a slip cannot lose what was typed.
             */
            message: string;
        };
        /**
         * AppIdentity
         * @description Which module instance produced a result.
         */
        AppIdentity: {
            /**
             * Name
             * @description The module's name.
             */
            name: string;
            /**
             * Uuid
             * @description This instance's id.
             */
            uuid: string;
        };
        /** AppStatus */
        AppStatus: {
            /** App Name */
            app_name: string;
            /** Received At */
            received_at: number;
            /** Stale */
            stale: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "Alert" | "Emergency" | "Initializing..." | "Undefined";
            /** T */
            t: number;
            /** Uuid */
            uuid: string;
        };
        /** AppStatusTable */
        AppStatusTable: {
            /** Apps */
            apps: components["schemas"]["AppStatus"][];
            replay: components["schemas"]["ReplayStatus"];
            /** Server Time */
            server_time: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** AutoPauseBody */
        AutoPauseBody: {
            /**
             * Enabled
             * @description Pause the player when the frequency leaves the band.
             */
            enabled: boolean;
        };
        /**
         * Channel
         * @description One column of a labelled time window.
         *
         *     Flattened from p-SWAMP's three-row header, plus a precomputed display label so
         *     the client never has to join the parts itself.
         */
        Channel: {
            /** Channel */
            channel: string;
            /** Idx */
            idx: number;
            /** Label */
            label: string;
            /** Measurement */
            measurement: string;
            /** Station */
            station: string;
        };
        /**
         * ChannelCatalogue
         * @description Body of ``GET /api/time-window/channels``: every selectable channel.
         *
         *     Static for the life of the process, which is why it is a plain GET rather than
         *     something pushed down the socket. Declared as a model so the catalogue is in
         *     the contract -- it used to be built as a hand-dumped dict, which published as
         *     a bare `object` and left the client casting an implicitly-`any` response.
         */
        ChannelCatalogue: {
            /** Channels */
            channels: components["schemas"]["Channel"][];
        };
        /**
         * ChannelSelection
         * @description Body of POST /selection.
         */
        ChannelSelection: {
            /**
             * Channels
             * @description Channel indices, as listed by GET /channels.
             * @example [
             *       3,
             *       17,
             *       204
             *     ]
             */
            channels: number[];
        };
        /**
         * CommandAck
         * @description The reply to every command POST.
         *
         *     Deliberately NOT the resulting state. That arrives on whichever socket the
         *     page has open, on the server's own schedule, so state has exactly one path
         *     and there is no ordering for a client to reconcile between two of them. What
         *     this carries is only "the command was accepted, and here is what it was" --
         *     enough to log and to assert on, and nothing a page renders.
         *
         *     *Accepted* is all it promises. A handler that applies the command itself
         *     has applied it by now. A handler that hands it on (to a pipeline's player
         *     or module) has checked what it can and queued it for its receiver: the
         *     outcome arrives on the socket, or as an error notice carrying this
         *     ``request_id``.
         */
        CommandAck: {
            /** Applied */
            applied: string;
            /**
             * Request Id
             * @description Set when the command was handed on to a receiver: what answers or refuses it carries the same id.
             */
            request_id?: string | null;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * ErrorNotice
         * @description An ``ErrorEvent`` from one of the client's runs, with the app it came from.
         */
        ErrorNotice: {
            /**
             * App
             * @description The app whose pipeline it came from, e.g. 'pmu-test-streamer'.
             */
            app: string;
            /**
             * Detail
             * @description The cause, e.g. 'Type: text'.
             * @default null
             */
            detail: string | null;
            /**
             * Id
             * @description Unique per notice: the tray dismisses and de-duplicates by it.
             */
            id: string;
            /**
             * Message
             * @description One line for a person.
             */
            message: string;
            /**
             * Request Id
             * @description The command it answers, if any.
             * @default null
             */
            request_id: string | null;
            /**
             * Source
             * @description Who saw it: 'player', or a module's name.
             */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             * @description When the failure was seen.
             */
            timestamp: string;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** Excursion */
        Excursion: {
            /**
             * Auto Pause
             * @description The player is paused when the frequency leaves the band.
             */
            auto_pause: boolean;
            /**
             * Band Hz
             * @description How far from nominal still counts as in band.
             */
            band_hz: number;
            /**
             * Deviation Hz
             * @description Mean frequency minus nominal.
             */
            deviation_hz: number | null;
            /**
             * Excursions
             * @description Excursions out of the band seen so far.
             */
            excursions: number;
            /**
             * In Band
             * @description The mean frequency is within the band.
             */
            in_band: boolean;
        };
        /** ExcursionResult */
        ExcursionResult: {
            app: components["schemas"]["AppIdentity"];
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Parameters
             * @description The module's settings.
             */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @description Set when this result answers a command.
             * @default null
             */
            request_id: string | null;
            result: components["schemas"]["Excursion"];
            /**
             * Stream
             * @description The `stream` of the input this result was computed from; null for an answer to a command.
             * @default null
             */
            stream: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the result is about.
             */
            timestamp: string;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /**
         * FrameStats
         * @description The statistics of one instant.
         */
        FrameStats: {
            /**
             * Angle Spread Deg
             * @description Largest minus smallest voltage angle.
             */
            angle_spread_deg: number | null;
            /** Max Frequency Hz */
            max_frequency_hz: number | null;
            /**
             * Mean Frequency Hz
             * @description Mean of the stations' frequencies.
             */
            mean_frequency_hz: number | null;
            /** Mean Voltage Kv */
            mean_voltage_kv: number | null;
            /** Min Frequency Hz */
            min_frequency_hz: number | null;
            /**
             * N Stations
             * @description Stations with a frequency value in this frame.
             */
            n_stations: number;
        };
        /** FrameStatsResult */
        FrameStatsResult: {
            app: components["schemas"]["AppIdentity"];
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Parameters
             * @description The module's settings.
             */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @description Set when this result answers a command.
             * @default null
             */
            request_id: string | null;
            result: components["schemas"]["FrameStats"];
            /**
             * Stream
             * @description The `stream` of the input this result was computed from; null for an answer to a command.
             * @default null
             */
            stream: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the result is about.
             */
            timestamp: string;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /** GridBranch */
        GridBranch: {
            /** From Bus */
            from_bus: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "line" | "trafo";
            /** Name */
            name: string;
            /** To Bus */
            to_bus: string;
        };
        /** GridBus */
        GridBus: {
            /** Area */
            area?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name: string;
            /** V Nom */
            v_nom?: number | null;
        };
        /**
         * GridModel
         * @description Static topology. Served over HTTP rather than a socket: it never changes,
         *     it is worth caching, and putting it on the socket would make every page's
         *     hook handle a second message shape for no benefit.
         */
        GridModel: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Branches */
            branches: components["schemas"]["GridBranch"][];
            /** Buses */
            buses: components["schemas"]["GridBus"][];
            /** Pmus */
            pmus: components["schemas"]["PmuSite"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Reply to `GET /healthz`, the liveness/readiness probe.
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Island */
        Island: {
            /** Index */
            index: number;
            /** Mean Freq */
            mean_freq: number | null;
            /** Stations */
            stations: string[];
        };
        /** IslandingParameters */
        IslandingParameters: {
            /** Eval Freq */
            eval_freq: number;
            /** Mean Threshold */
            mean_threshold: number;
            /** Window Length */
            window_length: number;
        };
        /** IslandingResult */
        IslandingResult: {
            /** App Name */
            app_name: string;
            /** App Uuid */
            app_uuid: string;
            /** Islands */
            islands: components["schemas"]["Island"][];
            parameters: components["schemas"]["IslandingParameters"];
            /**
             * Status
             * @enum {string}
             */
            status: "OK" | "Alert" | "Emergency" | "Initializing..." | "Undefined";
            /** T */
            t: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * IslandingState
         * @description Both halves of the islanding page in one message.
         *
         *     Detection and alarms are separate concerns upstream -- different topics, one
         *     derived from the other -- but they change together and are read together, so
         *     splitting them across two sockets would only mean the page could render them
         *     inconsistently.
         *
         *     Declared here rather than in islanding/api.py, where it used to live: this
         *     module's whole job is to be the one place a message shape is named, and a
         *     shape defined next to its endpoint was the one exception.
         */
        IslandingState: {
            alarms: components["schemas"]["AlarmList"];
            /** @default null */
            islanding: components["schemas"]["IslandingResult"] | null;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * LineOutageEvent
         * @description One branch changing connection state, as the detector reports it.
         *
         *     ``stations`` and ``measurements`` come straight from the time window's
         *     header for the channels that flipped, so a single physical line trip
         *     normally appears with the station at each end -- the current on that branch
         *     goes to zero as seen from both.
         */
        LineOutageEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "disconnect" | "connect";
            /** Measurements */
            measurements: string[];
            /** Stations */
            stations: string[];
            /** T */
            t: number;
        };
        /**
         * LineOutageLog
         * @description Newest first. The detector is silent unless something changes, so this is
         *     a log of transitions rather than a snapshot of present state.
         */
        LineOutageLog: {
            /**
             * App Name
             * @default null
             */
            app_name: string | null;
            /**
             * App Uuid
             * @default null
             */
            app_uuid: string | null;
            /** Events */
            events: components["schemas"]["LineOutageEvent"][];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
            /**
             * Window Length
             * @default null
             */
            window_length: number | null;
        };
        /** Phasor */
        Phasor: {
            /** Ang */
            ang: number | null;
            /** Channel */
            channel: string;
            /**
             * Island
             * @default null
             */
            island: number | null;
            /** Mag */
            mag: number | null;
            /** Station */
            station: string;
        };
        /**
         * PhasorSnapshot
         * @description The most recent phasor per station.
         *
         *     ``mag_ref`` and ``ang_ref`` are sent rather than applied, so the client can
         *     offer per-unit and mean-angle-relative views as toggles -- which is what the
         *     Qt phasor plot does -- without the server having to guess which is wanted.
         */
        PhasorSnapshot: {
            /**
             * Ang Ref
             * @default null
             */
            ang_ref: number | null;
            /**
             * Mag Ref
             * @default null
             */
            mag_ref: number | null;
            /** Phasors */
            phasors: components["schemas"]["Phasor"][];
            /** T */
            t: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * PlayerStatus
         * @description Where a run's player is and what it can do. A page renders its controls
         *     from this, so it never shows a button that would be refused.
         */
        PlayerStatus: {
            /**
             * Can Seek
             * @description Seek, step and speed apply (replay mode).
             */
            can_seek: boolean;
            /**
             * Coverage End
             * @description Exclusive end of the recording; null when live.
             */
            coverage_end: string | null;
            /**
             * Coverage Start
             * @description Start of the recording; null when live.
             */
            coverage_start: string | null;
            /**
             * Cursor
             * @description The instant of the last frame played.
             */
            cursor: string | null;
            /**
             * Ended
             * @description The replay reached its end and stopped.
             */
            ended: boolean;
            /**
             * Error
             * @description Why the stream stopped, when a provider failed; null otherwise.
             * @default null
             */
            error: string | null;
            /**
             * Loop
             * @description The replay starts over at the end of the recording.
             */
            loop: boolean;
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Mode
             * @description 'replay' paces a recording; 'live' follows a live source and has no controls.
             * @enum {string}
             */
            mode: "live" | "replay";
            /** Paused */
            paused: boolean;
            /**
             * Range End
             * @description Exclusive end of a chunk being played; null otherwise.
             * @default null
             */
            range_end: string | null;
            /**
             * Source
             * @description The active source.
             */
            source: string;
            /**
             * Sources
             * @description Every source the player can switch to, in declared order.
             */
            sources: string[];
            /**
             * Speed
             * @description Speed multiplier; 1 is real time.
             */
            speed: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /**
         * PmuFrame
         * @description One instant of every channel in a stream.
         */
        PmuFrame: {
            /** @description The channel layout; `values` follows its column order. */
            header: components["schemas"]["PmuHeader"];
            /**
             * Mrid
             * @description The stream (a PDC, a recording).
             */
            mRID: string;
            /**
             * Seq
             * @description This frame's number in that pass, from 0. A gap means a frame was lost on the way. Set by the gateway.
             * @default null
             */
            seq: number | null;
            /**
             * Stream
             * @description The pass over the source this frame was read in; a seek, a loop or a source switch starts another. Set by the gateway.
             * @default null
             */
            stream: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @description The PMU time of this instant.
             */
            timestamp: string;
            /**
             * Values
             * @description One value per header column; null where NaN.
             */
            values: (number | null)[];
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /**
         * PmuHeader
         * @description The channel layout of a stream: one entry per column of a frame.
         *
         *     The label rows are the ones p-SWAMP's ``Indexer`` queries, so
         *     ``columns(measurement="f")`` selects inputs the same way here.
         */
        PmuHeader: {
            /**
             * Channel
             * @description Per column: the phasor or signal name.
             */
            channel: string[];
            /**
             * Cimreferenceid
             * @description The grid (CIM) data that applies to this layout. Set by the gateway, never by a provider.
             * @default null
             */
            cimReferenceId: string | null;
            /**
             * Data Rate
             * @description Frames per second.
             */
            data_rate: number;
            /**
             * Header Id
             * @description Content hash of the layout; equal layouts share it.
             */
            readonly header_id: string;
            /**
             * Measurement
             * @description Per column: "f", "df", "<name>_Magnitude" or "<name>_Angle".
             */
            measurement: string[];
            /**
             * Station
             * @description Per column: the station (PMU) the value is from.
             */
            station: string[];
            /**
             * Units
             * @description Per column: the unit of the value.
             */
            units: string[];
        };
        /** PmuSite */
        PmuSite: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
        /**
         * PmuStreamState
         * @description What the page renders, pushed on connect and after every change. Its parts
         *     are the core's messages as they are, so the browser's types are generated
         *     from the same classes.
         */
        PmuStreamState: {
            /** @description The excursion module's latest result. */
            excursion: components["schemas"]["ExcursionResult"] | null;
            /** @description The frame at the cursor, with its layout. */
            frame: components["schemas"]["PmuFrame"] | null;
            /**
             * Frame Count
             * @description Frames in the recording; null when live.
             */
            frame_count: number | null;
            /**
             * Frame Index
             * @description 0-based position of the frame in the recording; null when live.
             */
            frame_index: number | null;
            /** @description Where the player is and which controls apply. */
            player: components["schemas"]["PlayerStatus"];
            /** @description The frame statistics for (about) that frame. */
            stats: components["schemas"]["FrameStatsResult"] | null;
            /** @description The answer to this client's last range summary. */
            summary: components["schemas"]["RangeSummaryResult"] | null;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** RangeSummary */
        RangeSummary: {
            /** End Offset S */
            end_offset_s: number;
            /**
             * Frames
             * @description Frames in the range.
             */
            frames: number;
            /** Max Frequency Hz */
            max_frequency_hz: number;
            /** Mean Frequency Hz */
            mean_frequency_hz: number;
            /** Min Frequency Hz */
            min_frequency_hz: number;
            /** Offset S */
            offset_s: number;
            /** Source */
            source: string;
        };
        /** RangeSummaryResult */
        RangeSummaryResult: {
            app: components["schemas"]["AppIdentity"];
            /**
             * Mrid
             * @default null
             */
            mRID: string | null;
            /**
             * Parameters
             * @description The module's settings.
             */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @description Set when this result answers a command.
             * @default null
             */
            request_id: string | null;
            result: components["schemas"]["RangeSummary"];
            /**
             * Stream
             * @description The `stream` of the input this result was computed from; null for an answer to a command.
             * @default null
             */
            stream: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the result is about.
             */
            timestamp: string;
            /**
             * Version
             * @default v1
             * @constant
             */
            version: "v1";
        };
        /**
         * ReferenceSubappState
         * @description The single message shape pushed to a client on connect and every change.
         *
         *     Keys are snake_case on the wire, and stay that way: the page reads the
         *     generated type for this model rather than a renamed mirror of it.
         */
        ReferenceSubappState: {
            /**
             * Count
             * @description This client's count. Replace with real state.
             */
            count: number;
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /**
         * ReplayStatus
         * @description State of the PMU source feeding every application.
         */
        ReplayStatus: {
            /** Cursor */
            cursor: number;
            /** Data Rate */
            data_rate: number;
            /** Duration */
            duration: number;
            /** N Channels */
            n_channels: number;
            /** N Samples */
            n_samples: number;
            /** Playing */
            playing: boolean;
            /** Position */
            position: number;
            /** Source */
            source: string;
        };
        /** SeekBody */
        SeekBody: {
            /**
             * End Offset S
             * @description Stop here: play a chunk.
             */
            end_offset_s?: number | null;
            /**
             * Offset S
             * @description Seconds from the start of the recording.
             */
            offset_s: number;
            /**
             * Play
             * @description Also start playing.
             * @default false
             */
            play: boolean;
        };
        /** SourceBody */
        SourceBody: {
            /**
             * Name
             * @description One of PlayerStatus.sources.
             */
            name: string;
        };
        /** SpeedBody */
        SpeedBody: {
            /**
             * Speed
             * @description Speed multiplier; 1 is real time.
             */
            speed: number;
        };
        /** StepBody */
        StepBody: {
            /**
             * N
             * @description Frames to step; negative steps back.
             */
            n: number;
        };
        /** SummaryBody */
        SummaryBody: {
            /**
             * End Offset S
             * @description Exclusive end, in seconds from the start.
             */
            end_offset_s: number;
            /**
             * Offset S
             * @description Seconds from the start of the recording.
             */
            offset_s: number;
            /**
             * Source
             * @description The recording to read: one of PlayerStatus.sources.
             */
            source: string;
        };
        /**
         * TimeWindowSlice
         * @description A slice of the client's measurement window.
         *
         *     ``series`` is column-major -- one list per channel, parallel to ``channels``.
         *     That is the layout a streaming chart wants; row-major would force the client
         *     to transpose a matrix of a few hundred thousand numbers on every update.
         *
         *     ``mode`` is what keeps this affordable. A full window is tens of thousands of
         *     numbers and re-sending it several times a second is megabytes per second per
         *     client; an "append" carries only the samples added since the last message.
         *     The server sends "full" on connect and whenever the selection changes, and
         *     "append" the rest of the time. ``seq`` counts messages so a client can tell
         *     it missed one and ask for a fresh "full".
         */
        TimeWindowSlice: {
            /**
             * Channels
             * @default null
             */
            channels: components["schemas"]["Channel"][] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "full" | "append";
            /**
             * N Samples
             * @default null
             */
            n_samples: number | null;
            /**
             * Sampling Rate
             * @default null
             */
            sampling_rate: number | null;
            /** Seq */
            seq: number;
            /** Series */
            series: (number | null)[][];
            /** T */
            t: (number | null)[];
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    grid_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridModel"];
                };
            };
        };
    };
    islanding_acknowledge: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    islanding_annotate: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    islanding_silence: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path: {
                alarm_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_auto_pause: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoPauseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_pause: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_play: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_seek: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_source: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_speed: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_step: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pmu_test_streamer_summary: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description The client has no running pipeline: its page is not open. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The command does not apply in the pipeline's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_subapp_bump: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_subapp_reset: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_window_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelCatalogue"];
                };
            };
        };
    };
    time_window_resync: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_window_select_channels: {
        parameters: {
            query: {
                /** @description The browser's client id -- the same value its WebSockets send, which is what makes a command apply to the pipeline the page is watching. */
                client_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
